title: SONAR XR
description: Documentation site for the SONAR XR project.
theme: just-the-docs
color_scheme: dark

url: https://sonarvrc.github.io

aux_links:
  SONAR XR LinkTree: https://linktr.ee/sonarxr
